# Generated by Django 4.1.6 on 2023-02-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tarefas_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='lider',
            field=models.CharField(max_length=100),
        ),
    ]
