# Generated by Django 4.1.6 on 2023-02-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tarefas_lider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='lider',
        ),
    ]
