# Generated by Django 4.1.6 on 2023-02-02 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_tarefas_grupo_remove_tarefas_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='integrante1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
