# Generated by Django 4.1.6 on 2023-02-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_topic_tarefas_topic_tarefas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='tarefas',
        ),
        migrations.CreateModel(
            name='conjTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarefa', models.ManyToManyField(to='core.tarefas')),
                ('Topico', models.ManyToManyField(to='core.topic')),
            ],
        ),
    ]
