# Generated by Django 4.1.6 on 2023-02-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_grupos_nome_grupos_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupos',
            old_name='Nome',
            new_name='Gp',
        ),
    ]
