# Generated by Django 4.1.6 on 2023-02-03 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_nome_grupos_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='Participantes',
            field=models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL),
        ),
    ]
