# Generated by Django 4.1.6 on 2023-02-02 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='fim',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupos'),
        ),
    ]
