# Generated by Django 4.1.6 on 2023-02-02 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarefas_fim_alter_tarefas_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='integrante2',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='integrante3',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='integrante4',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='integrante5',
        ),
        migrations.AlterField(
            model_name='grupos',
            name='integrante1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
