# Generated by Django 4.1.6 on 2023-02-02 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_grupos_integrante1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='integrante1',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='nomegp',
        ),
        migrations.AddField(
            model_name='grupos',
            name='Nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupos',
            name='Participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupos',
            name='Ultima',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.grupos'),
            preserve_default=False,
        ),
    ]
