# Generated by Django 4.1.6 on 2023-02-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_grupos_integrante1_remove_grupos_nomegp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupos',
            old_name='Ultima',
            new_name='Criado',
        ),
        migrations.RenameField(
            model_name='tarefas',
            old_name='fim',
            new_name='Prazo',
        ),
        migrations.AddField(
            model_name='grupos',
            name='Alterado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
