# Generated by Django 4.1.6 on 2023-02-02 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tarefas_datainicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='Prazo',
            new_name='Entregue',
        ),
        migrations.AddField(
            model_name='tarefas',
            name='prazofinal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
