# Generated by Django 4.1.6 on 2023-02-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_topic_tarefas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='tarefas',
        ),
        migrations.AddField(
            model_name='topic',
            name='tarefas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tarefas'),
            preserve_default=False,
        ),
    ]
