# Generated by Django 4.1.6 on 2023-02-02 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_topic_tarefas_conjtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='grupos',
            name='Nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='Participantes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
