# Generated by Django 4.1.6 on 2023-02-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_creategp_alter_grupos_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='Nome',
        ),
        migrations.AddField(
            model_name='grupos',
            name='Nome',
            field=models.ManyToManyField(to='core.creategp'),
        ),
    ]
